"""Add image_url to post

Revision ID: 677642dbaf14
Revises: 6ec48a6a02d6
Create Date: 2025-05-15 15:13:13.615222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677642dbaf14'
down_revision = '6ec48a6a02d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
